jobs:
  build:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
          coverprofile: coverage.txt
      - run:
          name: Coverage Report
          command: |
            bash <(curl -s https://codecov.io/bash)
orbs:
  go: circleci/go@1.4.0
version: 2.1
workflows:
  main:
    jobs:
      - build